### ISSUE TITLE
AES unscrambling still possible?

### ISSUE THREAD

**Issue by ESEEG** [MAVProxyUser/DJI_ftpd_aes_unscramble#10]
Last update on Aug 25, 2017 and I cannot unscramble anything. 
Has this project been abandoned?

**Comment by MAVProxyUser** [comment]
my dude you are YEARS late to the scene. Sorry my man.

**Comment by matemaciek** [comment]
I was able to unscrable newest (well, still quite old) Spark logs after changing AES key to the one from #7 : https://github.com/matemaciek/DJI_ftpd_aes_unscramble/tree/patch-1
