### ISSUE TITLE
Incorrect header and padding

### ISSUE THREAD

**Issue by jezzab** [MAVProxyUser/DJI_ftpd_aes_unscramble#2]
The first 16 bytes of the header are incorrect after decryption. Also the decrypted file is padded and increases padding over X bytes.

The header needs to be corrected as follows (thanks to darksimpson for this one)

Bytes 0x00 - 0x09 needs XOR 0x30 + the position
Bytes 0x0A - 0x0F needs XOR 0x57 + the position

eg code:
```

        // Descramble first 16 bytes
        for (int i = 0x00; i < 0x0A; i++)
        {
            array[i] ^= (byte)(0x30 + i);
        }
        for (int i = 0x0A; i < 0x10; i++)
        {
            array[i] ^= (byte)(0x57 + i);
        }
```
if openssl as per the examples on the readme is used the file is not padded and correct bar the header above

**Comment by MAVProxyUser** [comment]
Fixed via these two commits. 

https://github.com/MAVProxyUser/DJI_ftpd_aes_unscramble/commit/45181aeb97b14cc03e7db5807d56b24f38bea8f4

https://github.com/MAVProxyUser/DJI_ftpd_aes_unscramble/commit/93537fdec26435537399ea8595e0eee8725f5759
